=== Chugani05/1-DAW/LND/unidad 05/tareas/escuela.dtd
<!ELEMENT escuela (clase+)>
<!ELEMENT clase (profesor, alumno+)>
<!ELEMENT profesor (nombre, apellidos?)>
<!ELEMENT alumno (nombre, apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT pizarra (#PCDATA)>

=== Chugani05/1-DAW/Lenguaje de Marcas/unidad 05/tareas/escuela.xml
<!DOCTYPE escuela SYSTEM "escuela.dtd">
    <escuela>
        <clase nombre="Matemáticas" tiene_pizarra="true">
            <profesor>
                <nombre>Juan</nombre>
                <apellidos>Pérez</apellidos>
            </profesor>
            <alumnos>
                <alumno>
                    <nombre>María</nombre>
                    <apellidos>Gómez</apellidos>
                </alumno>
                <alumno>
                    <nombre>Pedro</nombre>
                    <apellidos>López</apellidos>
                </alumno>
            </alumnos>
        </clase>
        <clase nombre="Física" tiene_pizarra="false">
            <profesor>
                <nombre>Luis</nombre>
                <apellidos>Martinez</apellidos>
            </profesor>
            <alumnos>
                <alumno>
                    <nombre>Laura</nombre>
                    <apellidos>Gonzales</apellidos>
                </alumno>
                <alumno>
                    <nombre>Juan</nombre>
                    <apellidos>Dominguez</apellidos>
                </alumno>
            </alumnos>
        </clase>
    </escuela>
